### ISSUE TITLE
models/actions/RollDice.model.bxb

### ISSUE THREAD

**Issue by ktx2047** [bixbydevelopers/capsule-sample-dice#8]
여기에 나와있는 코드 내용중

type(calculation)의 의미가 뭔가요?

type중에 calculation 이라는 타입이 존재하는건가요?

관련 내용이 있으면 태그해 주시면 감사하겠습니다.

**Comment by rogerkibbe** [comment]
This is outlined in the manual at bixbydevelopers.com- types are discussed here: https://bixbydevelopers.com/dev/docs/reference/type/action.type
